# Generated by Django 3.2.5 on 2022-03-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommended', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommended',
            name='recommended_name',
            field=models.CharField(max_length=200, verbose_name=['X-Ray C Arm', 'mammography machine - Platinum ANALOG', 'in Stock Hc-10b Air/Oxgen Blender CPAP Hbky Portable Infant Medical Equipment', 'emergency bag', 'The Bovie Derm Desiccator', 'Medical Infant T-Piece Resusitation, Newborn Resuscitation with Mask and Tube, Neonatal Equipment', 'in Stock CE Certificate Hospital Vg70 Respiratory ICU Medical Breathing Machine Equipment for Infant', 'Hospital Newborn Baby Infant Radiant Warmer Medical Equipment for Good Sale', 'Lab Equipment with Binocular Price Optical Stereo Microscope']),
        ),
    ]
