# Generated by Django 3.2.5 on 2022-03-07 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_user_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_Company',
            new_name='Company',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_Doctor',
            new_name='Doctor',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_user',
            new_name='user',
        ),
    ]
