# Generated by Django 3.2.5 on 2022-04-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('Category', models.CharField(max_length=25)),
                ('price', models.CharField(max_length=10, null=True)),
                ('Production_country', models.CharField(max_length=50)),
                ('image', models.ImageField(null=True, upload_to='media_files/')),
                ('recommended_name', models.CharField(max_length=1000)),
            ],
        ),
    ]
