# Generated by Django 3.2.5 on 2022-04-25 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ref_code',
        ),
    ]
