# Generated by Django 3.2.5 on 2022-04-27 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_order_ref_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='recommended_name',
        ),
        migrations.CreateModel(
            name='Recommended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recomended_devices', models.CharField(max_length=1000)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.products')),
            ],
        ),
    ]
