# Generated by Django 3.2.5 on 2022-04-27 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220427_0536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommended',
            name='recomended_devices',
        ),
        migrations.AddField(
            model_name='recommended',
            name='recomended_devices',
            field=models.ManyToManyField(related_name='aa', to='home.Products'),
        ),
    ]
