# Generated by Django 3.2.5 on 2022-05-07 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_orderitem_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
    ]
