# Generated by Django 3.2.5 on 2022-04-25 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='image',
            new_name='logo',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='user',
            new_name='person',
        ),
        migrations.RemoveField(
            model_name='company',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='company',
            name='last_name',
        ),
        migrations.AddField(
            model_name='company',
            name='company',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='authentications.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=15),
        ),
    ]
