# Generated by Django 3.2.5 on 2022-05-08 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0002_auto_20220425_0601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='person',
        ),
    ]
