# Generated by Django 3.2.5 on 2022-05-07 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0002_auto_20220425_0601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company',
        ),
        migrations.RemoveField(
            model_name='person',
            name='person',
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Company', to='authentications.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Person', to='authentications.user'),
            preserve_default=False,
        ),
    ]
