# Generated by Django 3.2.5 on 2022-05-07 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0003_auto_20220507_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
        migrations.RemoveField(
            model_name='person',
            name='user',
        ),
        migrations.AddField(
            model_name='company',
            name='company',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='authentications.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='person',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
