# Generated by Django 3.2.5 on 2022-05-08 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0003_remove_person_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company',
            new_name='auth_user_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_company',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_person',
        ),
        migrations.AddField(
            model_name='person',
            name='auth_user_id',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='authentications.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[(1, 'Admin'), (2, 'Customer'), (3, 'Company')], default=2, max_length=255),
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('auth_user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
