# Generated by Django 3.2.5 on 2022-05-07 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0004_auto_20220507_0857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='person',
        ),
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='authentications.user'),
            preserve_default=False,
        ),
    ]
