# Generated by Django 3.2.5 on 2022-05-07 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0006_auto_20220507_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='person',
        ),
    ]
