# Generated by Django 3.2.5 on 2022-02-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='Products',
            old_name='code',
            new_name='Name',
        ),
        migrations.AddField(
            model_name='Products',
            name='Production_country',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='Products',
            name='image',
            field=models.ImageField(default='', upload_to='media_files/'),
            preserve_default=False,
        ),
    ]
