# Generated by Django 3.2.5 on 2022-03-06 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220221_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(null=True, upload_to='media_files/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
