# Generated by Django 3.2.5 on 2022-03-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220306_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='recommended_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
