# Generated by Django 3.2.5 on 2022-03-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products_recommended_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='recommended_name',
            field=models.CharField(max_length=1000),
        ),
    ]
